### ISSUE TITLE
User does not have sufficient permissions for this profile.

### ISSUE THREAD

**Issue by ikramooe** [tightenco/nova-google-analytics#50]
i keep getting this error " User does not have sufficient permissions for this profile. error 403 " even tough the email i found in the json file i did add it as an analyst

**Comment by krievley** [comment]
Since the application looks for your credentials in the storage folder ([docs here](https://github.com/spatie/laravel-analytics/blob/main/config/analytics.php)), it's possible your application isn't able to access it? I would try running `php artisan storage:link` ([docs](https://laravel.com/docs/9.x/filesystem#the-public-disk)) to make sure that your credentials file can be accessed by the system. Also make sure that the view id is correctly set in the `.env` file.
